### ISSUE TITLE
Using english.bdf or french.bdf as an template could result in error

### ISSUE THREAD

**Issue by komascript** [TeX-Live/babelbib#2]
I know, that language options to `babelbib` should be used only to load new language definition files. However section 6 of the manual recommends to copy an existing one and change that new file. If someone uses `english.bdf` or `french.bdf` as template, the `\makeatother` in those files would break `babelbib`. As an example, you can simply use `english` or `french` as an option, e.g.:

```latex
\documentclass{article}
\usepackage[english]{babel}
\usepackage[fixlanguage,english]{babelbib}
\begin{document}
\end{document}
```

would result in an error

```log
LaTeX Error: Command \@ already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.116   \newcommand\@s
                      electbiblanguage[1]{%
```

I would suggest to change `english.bdf` lines 

```latex
\makeatletter
\@ifpackageloaded{french}{}{\newcommand\bibsenglish{}}
\makeatother
```

to 

```latex
\csname @ifpackageloaded\endcsname{french}{}{\newcommand\bibsenglish{}}
```

and similar for `french.bdf` to avoid the `\makeatother`. But there are many other solutions for the tiny problem.

**Comment by norbusan** [comment]
Should be fixed with v1.34 which I just uploaded to CTAN.
