### ISSUE TITLE
sort&compress in babelbib

### ISSUE THREAD

**Issue by castellanos-angel** [TeX-Live/babelbib#3]
Dear sirs,

I am currently writing my Ph.D. thesis in Spanish and using babelbib. Is there a way to implement the sort&compress feature of natbib in babelbib?

Thank you very much in advance.

Regards,
Angel

**Comment by komascript** [comment]
`babelbib` is compatible enough with `natbib` to load `natbib` to have `sort&compress`:
```latex
\documentclass{article}

\usepackage[english]{babel}
\usepackage{babelbib}
\usepackage[numbers,sort&compress]{natbib}

\begin{document}
\section{Test}
\cite{aksin}, \cite{bertram}, \cite{doody}, \cite{gillies}

\cite{gillies,doody,bertram,aksin,glashow}
\bibliographystyle{babplain}
\bibliography{biblatex-examples}
\end{document}
```

**Comment by castellanos-angel** [comment]
Thank you very much for your answer.

Best regards,
Ángel

*::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::*
*::::::*
*Dr. José Ángel Castellanos Reyes*
e-mail: ***@***.***
Skype: angel.castellanos.reyes
ORCID: https://orcid.org/0000-0002-4777-9993
ResearchGate: https://www.researchgate.net/profile/Jose-Castellanos-Reyes-2
Google Scholar:
https://scholar.google.com/citations?user=bb2631YAAAAJ&hl=es&oi=ao
